[package]
name = "fluenceTest"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "fluenceTest"
path = "src/main.rs"

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
marine-rs-sdk = "0.7.1"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
